createPokemon("Geodude", "Tackle", "Fire Punch", "Earthquake", ElementType::COLORLESS)
createPokemon("Mew", "Pound", "Psychic", "Aura Sphere", ElementType::PSYCHIC)
createPokemon("Mewtwo", "Confusion", "Psychic", "Psystrike", ElementType::PSYCHIC)
createPokemon("Gengar", "Shadow Punch", "Night Shade", "Shadow Ball", ElementType::PSYCHIC)
createPokemon("Butterfree", "Gust", "Psybeam", "Psychic", ElementType::PSYCHIC)
createPokemon("Pikachu", "Nuzzle", "Discharge", "Thunder", ElementType::LIGHTNING)
createPokemon("Pichu", "Charge", "Thunder Shock", "Thunder Punch", ElementType::LIGHTNING)
createPokemon("Charizard", "Tackle", "Rock Throw", "Landslide", ElementType::FIRE)
createPokemon("Vulpix", "Ember", "Flamethrower", "Fire Blast", ElementType::FIRE)
createPokemon("Jolteon", "Thunder Shock", "Pin Missile", "Thunder Fang", ElementType::LIGHTNING)
createPokemon("Parichirisu", "Spake", "Electro Ball", "Discharge", ElementType::LIGHTNING)
createPokemon("Chimchar", "Ember", "Fire Spin", "Flamethrower", ElementType::FIRE)
createPokemon("Charmander", "Scratch", "Flamethrower", "Flare Blitz", ElementType::FIRE)
createPokemon("Magmar", "Ember", "Flame Wheel", "Fire Blast", ElementType::FIRE)
createPokemon("Bulbasaur", "Razor Leaf", "Seed Bomb", "Solar Beam", ElementType::GRASS)
createPokemon("Alakazam", "Confusion", "Psybeam", "Psychic", ElementType::PSYCHIC)
createPokemon("Staryu", "Water Gun", "Surf", "Brine", ElementType::WATER)
createPokemon("Dragonite", "Water Gun", "Aqua Tail", "Dive", ElementType::WATER)
createPokemon("Psyduck", "Water Gun", "Water Pulse", "Aqua Tail", ElementType::WATER)
createPokemon("Arcanine", "Bite", "Fire Fang", "Reversal", ElementType::FIRE)
createPokemon("Snorlax", "Flail", "Bite", "Giga Impact", ElementType::COLORLESS)
createPokemon("Cresselia", "Confusion", "Psybeam", "Moonblast", ElementType::PSYCHIC)
createPokemon("Darkrai", "Ominous Wind", "Quick Attack", "Dream Eater", ElementType::COLORLESS)
createPokemon("Entei", "Ember", "Sacred Fire", "Fire Blast", ElementType::FIRE)
createPokemon("Arceus", "Earth Power", "Extreme Speed", "Judgement", ElementType::COLORLESS)
createPokemon("Lapras", "Surf", "Ice Beam", "Water Pulse", ElementType::COLORLESS)
createPokemon("Suicune", "Water Gun", "Surf", "Blizzard", ElementType::WATER)
createPokemon("Zapdos", "Peck", "Thunder Shock", "Zap Cannon", ElementType::LIGHTNING)
createPokemon("Turtwig", "Tackle", "Razor Leaf", "Leaf Storm", ElementType::GRASS)
createPokemon("Wobbuffet", "Tackle", "Counter", "Splash", ElementType::COLORLESS)
createPokemon("Registeel", "Bulldoze", "Stomp", "Hyper Beam", ElementType::COLORLESS)
createPokemon("Diglett", "Scratch", "Mud-Slap", "Earth Power", ElementType::GRASS)
createPokemon("Squirtle", "Tackle", "Water Gun", "Aqua Tail", ElementType::WATER)
createPokemon("Wartortle", "Water Gun", "Aqua Tail", "Whirlpool", ElementType::WATER)
createPokemon("Blastoise", "Headbutt", "Aqua Tail", "Hydro Pump", ElementType::WATER)
createPokemon("Eevee", "Tackle", "Swift", "Takedown", ElementType::COLORLESS)
createPokemon("Scyther", "Quick Attack", "Double Hit", "X-Scissor", ElementType::GRASS)
createPokemon("Gyrados", "Whirlpool", "Aqua Tail", "Hydropump", ElementType::WATER)
createPokemon("Tauros", "Horn Attack", "Thrash", "Giga Impact", ElementType::COLORLESS)
createPokemon("Dodrio", "Quick Attack", "Thrash", "Hyper Beam", ElementType::COLORLESS)
createPokemon("Pidgeot", "Gust", "Wing Attack", "Air Slash", ElementType::COLORLESS)
createPokemon("Rattata", "Tackle", "Super Fang", "Hyper Fang", ElementType::COLORLESS)
createPokemon("Ninetales", "Ember", "Fire Blast", "Flamethrower", ElementType::FIRE)
createPokemon("Machop", "Strength", "Double-edge", "Low Kick", ElementType::COLORLESS)
createPokemon("Meowth", "Fury Swipes", "Scratch", "Fake Out", ElementType::COLORLESS)
createPokemon("Golduck", "Aqua Jet", "Hydro Pump", "Aqua Tail", ElementType::WATER)
createPokemon("Mankey", "Tackle", "Headbutt", "Thrash", ElementType::COLORLESS)
createPokemon("Magicarp", "Splash", "Tackle", "Flail", ElementType::WATER)// make splash 0 since it's a useless move
createPokemon("Zubat", "Astonish", "Air Slash", "Quick Attack", ElementType::COLORLESS)
createPokemon("Jynx", "Lick", "Ice Punch", "Psychic", ElementType::PSYCHIC)
createPokemon("Stunfisk", "Charge", "Discharge", "Spark", ElementType::LIGHTNING)
createPokemon("Gastly", "Shadowball", "Smog", "Lick", ElementType::PSYCHIC)
createPokemon("Omanyte", "Surf", "Water Gun", "Bubble", ElementType::WATER)
createPokemon("Raikou", "Thunderbolt", "Thunder", "Shock", ElementType::LIGHTNING)
createPokemon("Deino", "Headbutt", "Rock Throw", "Bite", ElementType::COLORLESS)
*/

